baseURL = "https://bradackerman.com/"
languageCode = "en-us"
title = "Concrete Cows"
theme = "ananke"
pygmentsCodeFences = true
pygmentsUseClasses = true
fractions = true
footnoteReturnLinkContents = "↩"
[params]
#  favicon = ""
  description = "Brad Ackerman's technical blog"
#  facebook = ""
  twitter = "https://twitter.com/bsa"
#  instagram = ""
#  youtube = ""
  github = "https://github.com/backerman/"
#  gitlab = ""
#  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-light-gray"
  body_classes = "bg-near-white"
  custom_css = ["css/overrides.css", "css/syntax.css" ]
#  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
#  recent_posts_number = 2

